version: '3.4'

services:
  craftech-back:
    image: django
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    networks:
      lan:
        ipv4_address: 192.168.0.6

  craftech-front:
    image: reactjs
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      lan:
        ipv4_address: 192.168.0.5

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"